set_property IOSTANDARD LVDS [get_ports clk_n]
set_property IOSTANDARD LVDS [get_ports clk_p]
set_property PACKAGE_PIN AD11 [get_ports clk_n]
set_property PACKAGE_PIN AD12 [get_ports clk_p]
set_property PACKAGE_PIN AA12 [get_ports reset]
set_property IOSTANDARD LVCMOS15 [get_ports reset]
set_property PACKAGE_PIN AG5 [get_ports start]
set_property IOSTANDARD LVCMOS15 [get_ports start]
